name: Daily Auto Commit with 23f2004089@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '0 12 * * *'  # 12:00 UTC daily
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository with token
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }}
        
    - name: Setup Git config for 23f2004089@ds.study.iitm.ac.in
      run: |
        git config --local user.email "23f2004089@ds.study.iitm.ac.in"
        git config --local user.name "GitHub Actions"
        
    - name: Create or update daily file
      run: |
        echo "Daily update - $(date -u)" > daily_update.txt
        echo "Updated by GitHub Actions workflow" >> daily_update.txt
        
    - name: Commit and push changes
      run: |
        git add daily_update.txt
        git diff --staged --quiet && echo "No changes to commit" || (git commit -m "Daily auto-commit [23f2004089@ds.study.iitm.ac.in] - $(date -u)" && git push)
